easier_github_actions: Debug last step.

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -26,7 +26,7 @@ jobs:
     - name: Exit due to failure
       id: early_exit
       if: ${{ steps.build_tests.outputs.build_result != 0 }} || ${{ steps.build_tests.outputs.quick_run_result != 0 }}
-      run: exit 1
+      run: echo "Build error ${{ steps.build_tests.outputs.build_result != 0 }}. Run error ${{ steps.build_tests.outputs.quick_run_result != 0 }}" && exit 1
     - name: Report success
       id: success
       if: ${{ steps.build_tests.outputs.build_result == 0 }}
