easier_github_actions: Separate `build` and `run` into parts.

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -15,12 +15,19 @@ jobs:
       id: build_tests
       # Use action in root directory
       uses: ./
-    - name: Report Failure
-      id: failure
+    - name: Report build failure
+      id: build_failure
       if: ${{ steps.build_tests.outputs.build_result != 0 }}
-      # use exit 1 to report a failure
-      run: echo "Something went wrong. Exit status ${{ steps.build_tests.outputs.build_result }}" && exit 1
-    - name: Report Success
+      run: echo "Something went wrong. Exit status ${{ steps.build_tests.outputs.build_result }}."
+    - name: Report run failure
+      id: run_failure
+      if: ${{ steps.build_tests.outputs.quick_run_result != 0 }}
+      run: echo "The executable was built but running it produces an error. Exit status ${{ steps.build_tests.outputs.quick_run_result }}."
+    - name: Exit due to failure
+      id: early_exit
+      if: ${{ steps.build_tests.outputs.build_result != 0 }} || ${{ steps.build_tests.outputs.quick_run_result }}
+      run: exit 1
+    - name: Report success
       id: success
       if: ${{ steps.build_tests.outputs.build_result == 0 }}
       run: echo "Build result ${{ steps.build_tests.outputs.build_result }}"
